name: musi_link
description: "musi link - Connect through music."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  firebase_crashlytics: ^5.0.5
  http: ^1.2.0  # Para llamadas a la API
  flutter_secure_storage: ^10.0.0 # Para guardar el token de forma segura
  spotify: ^0.16.0              # Conexión a Spotify Web API
  flutter_web_auth_2: ^5.0.1   # Para abrir navegador en OAuth
  font_awesome_flutter: ^10.12.0 # Para iconos
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.0
  flutter_riverpod: ^3.3.1
  go_router: ^17.1.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconoApp.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
