name: musi_link
description: "MusiLink - Connect through music."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.11.5

dependencies:
  firebase_core: ^4.6.0
  firebase_analytics: ^12.3.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  firebase_crashlytics: ^5.2.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  http: ^1.2.0  # Para llamadas a la API
  flutter_secure_storage: ^10.0.0 # Para guardar el token de forma segura
  cloud_functions: ^6.2.0
  font_awesome_flutter: ^11.0.0 # Para iconos
  lucide_icons_flutter: ^3.1.13
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  image_picker: ^1.2.2
  firebase_storage: ^13.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/IconoApp1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/IconoApp.png"
  adaptive_icon_foreground_inset: 22
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
